server:
  port: 8080

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.messaging: DEBUG

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/charactorstore"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true

  messages:
    encoding: UTF-8

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      connect-timeout: 60000

jwt:
  signerKey: "bNo78aQUGPoYQ+n70bPKw0j7YKetwWSAInt7zyJr6OulSPWoKFLH3iW9PyFYoipU"
  exp-accessToken: 120
  exp-refreshToken: 720